version: "3.3"
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
    - "80:80"
  client:
    build:
      dockerfile: Dockerfile
      context: ./application
    container_name: client
  backend:
    build:
      dockerfile: Dockerfile
      context: ./Service
    container_name: backend
    env_file:
      - ./Service/.env
  mongo:
    image: "mongo"
    container_name: "mongo-db"
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./Service/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./Service/db/mongo/mongo-volume:/data/db

